package actions

const PLAYER_HEALTH = 100
const MONSTER_HEALTH = 100

const PLAYER_ATTACK_MIN_DAMAGE = 5
const PLAYER_ATTACK_MAX_DAMAGE = 10
const PLAYER_SPECIAL_ATTACK_MIN_DAMAGE = 10
const PLAYER_SPECIAL_ATTACK_MAX_DAMAGE = 20
const PLAYER_HEAL_MIN_VALUE = 10
const PLAYER_HEAL_MAX_VALUE = 20

const MONSTER_ATTACK_MIN_DAMAGE = 9
const MONSTER_ATTACK_MAX_DAMAGE = 13
